name: Nix CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

env:
  FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true
  NIX_CONFIG: |
    accept-flake-config = true
    extra-substituters = https://anmonteiro.nix-cache.workers.dev
    extra-trusted-public-keys = ocaml.nix-cache.com-1:/xI2h2+56rwFfKyyFVbkJSeGqSIYMC/Je+7XXqGKDIY=

jobs:
  check:
    runs-on: ubuntu-22.04
    permissions:
      id-token: write
      contents: read
    steps:
      - uses: actions/checkout@v6
      - uses: DeterminateSystems/nix-installer-action@v22
      - uses: DeterminateSystems/magic-nix-cache-action@v13
      - uses: DeterminateSystems/flake-checker-action@v12

      - name: Run `nix flake check`
        run: nix flake check

      - name: Run cargo check in dev shell
        run: nix develop -c cargo check

      - name: Run cargo test in dev shell
        run: nix develop -c cargo test
