name: Spelling

permissions:
  contents: read

on:
  push:
    branches: [main]
  pull_request:

env:
  FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true

jobs:
  spelling:
    name: Spell Check with Typos
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - name: Spell Check Repo
        uses: crate-ci/typos@685eb3d55be2f85191e8c84acb9f44d7756f84ab
